# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PAFCpp <- function(Cor_Matrix, N_Factors, Max_Iter = 1000L, Criterion = 0.0001) {
    .Call(`_EFAfactors_PAFCpp`, Cor_Matrix, N_Factors, Max_Iter, Criterion)
}

calculateData <- function(k, Shared_Comp, Shared_Load, Unique_Comp, Unique_Load) {
    .Call(`_EFAfactors_calculateData`, k, Shared_Comp, Shared_Load, Unique_Comp, Unique_Load)
}

calculateRMSE <- function(Pop, EigsData, NSamples, NPop, N) {
    .Call(`_EFAfactors_calculateRMSE`, Pop, EigsData, NSamples, NPop, N)
}

generateDistributions <- function(suppliedData, I, Npop) {
    .Call(`_EFAfactors_generateDistributions`, suppliedData, I, Npop)
}

sortData <- function(Data, Distributions) {
    .Call(`_EFAfactors_sortData`, Data, Distributions)
}

